permalink: pretty
exclude:
    - Vagrantfile
    - Rakefile.rb
    - chef
    - css/vendor/
    - css/sections/
    - css/variables.less
    - css/mixins.less
    - css/reset.less
    - images/favicons.sketch/
    - Gemfile
    - Gemfile.lock
    - vendor

include: [.htaccess]
safe: true

# lsi: true

title: "Christoph Hochstrasser"
homepage_post_count: 6
paginate: 5

markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false

disqus:
    shortname: "christophhochstrasser"

navigation:
    - label: Home
      link: /
      icon: ss-home
    - label: About me
      link: /about/me/
      icon: ss-heart
    - label: All articles
      link: /blog/
      icon: ss-notebook
