permalink: pretty
lessc: /usr/local/bin/lessc
exclude:
    - Vagrantfile
    - Rakefile.rb
    - .vagrant
    - chef
    - css/variables.less
    - css/mixins.less
ftp_host: christophh.net
ftp_dir: /www/home/www.christophh.net
lsi: true
