permalink: pretty
lessc: /usr/local/bin/lessc
exclude:
    - Vagrantfile
    - Rakefile.rb
    - .vagrant
    - chef
    - css/vendor/
    - css/sections/
    - css/variables.less
    - css/mixins.less

markdown: redcarpet

lsi: true

title: "Christoph Hochstrasser, Web Creator"

disqus:
    shortname: "christophhochstrasser"
