permalink: pretty
exclude:
    - Vagrantfile
    - Rakefile.rb
    - chef
    - less
    - images/favicons.sketch/
    - Gemfile
    - Gemfile.lock
    - vendor
    - .codekit-cache

include: [.htaccess, .well-known]
safe: true
# lsi: true

title: "Christoph Hochstrasser"
homepage_post_count: 6
paginate: 5
paginate_path: "page/:num/"

site_url: "https://www.christophh.net"

asset_base_urls:
    fonts: //d3rgic9i48f56z.cloudfront.net/fonts

assets:
    css_version: 2
    js_version: 1

markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false

disqus:
    shortname: "christophhochstrasser"

navigation:
    - label: Home
      link: /
      icon: ss-home
    - label: About me
      link: /about/me/
      icon: ss-heart
    - label: Hire me
      link: /hire/me/
      icon: ss-briefcase
    - label: All articles
      link: /blog/
      icon: ss-notebook
